/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as DishesRouteImport } from './routes/dishes'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PlanWeekStartRouteImport } from './routes/plan.$weekStart'
import { Route as PlanNextRouteImport } from './routes/plan.next'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesRoute = DishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanWeekStartRoute = PlanWeekStartRouteImport.update({
  id: '/plan/$weekStart',
  path: '/plan/$weekStart',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanNextRoute = PlanNextRouteImport.update({
  id: '/plan/next',
  path: '/plan/next',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dishes': typeof DishesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/plan/$weekStart': typeof PlanWeekStartRoute
  '/plan/next': typeof PlanNextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dishes': typeof DishesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/plan/$weekStart': typeof PlanWeekStartRoute
  '/plan/next': typeof PlanNextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/change-password': typeof ChangePasswordRoute
  '/dishes': typeof DishesRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/plan/$weekStart': typeof PlanWeekStartRoute
  '/plan/next': typeof PlanNextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/change-password'
    | '/dishes'
    | '/history'
    | '/login'
    | '/setup'
    | '/plan/$weekStart'
    | '/plan/next'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/change-password'
    | '/dishes'
    | '/history'
    | '/login'
    | '/setup'
    | '/plan/$weekStart'
    | '/plan/next'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/change-password'
    | '/dishes'
    | '/history'
    | '/login'
    | '/setup'
    | '/plan/$weekStart'
    | '/plan/next'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DishesRoute: typeof DishesRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  PlanWeekStartRoute: typeof PlanWeekStartRoute
  PlanNextRoute: typeof PlanNextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes': {
      id: '/dishes'
      path: '/dishes'
      fullPath: '/dishes'
      preLoaderRoute: typeof DishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$weekStart': {
      id: '/plan/$weekStart'
      path: '/plan/$weekStart'
      fullPath: '/plan/$weekStart'
      preLoaderRoute: typeof PlanWeekStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/next': {
      id: '/plan/next'
      path: '/plan/next'
      fullPath: '/plan/next'
      preLoaderRoute: typeof PlanNextRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DishesRoute: DishesRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  PlanWeekStartRoute: PlanWeekStartRoute,
  PlanNextRoute: PlanNextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
